# Generated by Django 3.1.7 on 2021-03-28 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subtask',
            name='color',
            field=models.CharField(default='#ffffff', max_length=10, verbose_name='color'),
        ),
        migrations.AlterField(
            model_name='todo',
            name='color',
            field=models.CharField(default='#ffffff', max_length=10, verbose_name='color'),
        ),
    ]
